server.port: 8080
server.max-http-header-size: 65536 # 64K

####################
# Report Generator #
####################
report.generator:
  template-filename: 'Template.xlsx'
  report-sheet-name: 'For'
  row-offset: 1
  column-offset: 0

#########################
# Generation Controller #
#########################
generation.controller:
  # Content Type
  response-content-type: 'application/octet-stream'

  # Headers
  response-headers:
    Content-Disposition: 'inline; filename=%FILENAME%'
    Access-Control-Allow-Origin: '*'
    Access-Control-Allow-Methods: 'GET, POST, DELETE, PUT, OPTIONS, HEAD'